"use client";

import { useState, type ReactNode } from 'react';
import Link from 'next/link';
import { ArrowRight, FlaskConical, Plus, CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { useDemo } from '@/components/demo/demo-context';
import { canEditPLM } from '@/lib/demo-scope';
import { lifecycle, newDevelopment, rdCost, rdIssues, rdHandover, rdSampleStatuses, type Work, type Workspace, type RDDevelopment } from '@/lib/plm-workspace';

const tabs = ['Brief', 'References', 'Discussions', 'Designs', 'Samples', 'BOM & costing', 'Development checks'];
const selectClass = 'h-10 w-full rounded-md border bg-background px-3 text-sm';
const money = (value: number) => value.toLocaleString('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 });
const uid = () => crypto.randomUUID();
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block space-y-2 text-sm"><span className="font-medium">{label}</span>{children}</label>; }
function Panel({ title, hint, children }: { title: string; hint?: string; children: ReactNode }) { return <section className="space-y-4 rounded-xl border bg-card p-5 shadow-sm"><div><h2 className="text-lg font-semibold">{title}</h2>{hint && <p className="mt-1 text-sm text-muted-foreground">{hint}</p>}</div>{children}</section>; }
function NumberField({ label, value, onChange, max }: { label: string; value: number; onChange: (v: number) => void; max?: number }) { return <Field label={label}><Input type="number" min={0} max={max} step="0.01" value={value} onChange={e => onChange(Math.max(0, Math.min(max ?? Number.MAX_SAFE_INTEGER, Number(e.target.value) || 0)))}/></Field>; }

export default function RDWorkspace({ data, work, onSelect, update }: { data: Workspace; work?: Work; onSelect: (w: Work) => void; update: (patch: Partial<Work>) => void }) {
    const { persona } = useDemo();
    const [tab, setTab] = useState(tabs[0]);
    const [search, setSearch] = useState('');
    const products = data.works.filter(w => w.stage >= 1);
    const rd = work?.rd;
    const editable = !!work && work.stage === 1 && canEditPLM(persona.role, 1);
    const save = (patch: Partial<RDDevelopment>) => { if (editable && rd) update({ rd: { ...rd, ...patch } }); };
    const selectedMaterials = rd ? Object.entries(rd.decisions).filter(([, d]) => d.status === 'Selected').map(([id]) => id) : [];
    const cost = rd ? rdCost(rd) : 0;
    const issues = rd ? [...rdIssues(rd), ...(!work?.sampleIds?.length ? ['Link a Product Library reference sample'] : []), ...(work?.blocker?.trim() ? [work.blocker] : [])] : [];
    function start(illustrative: boolean) {
        if (!work || !editable) return;
        const next = newDevelopment(work);
        if (illustrative) {
            const material = data.materials.find(m => work.materials.includes(m.id)) || data.materials[0];
            next.brief = `Develop ${work.name} from the client specification. Review fit, construction and material suitability before client presentation. Illustrative development scenario.`;
            next.sizes = 'XS–XXL'; next.colours = 'Navy / Charcoal'; next.target = 650;
            if (material) { next.decisions[material.id] = { status: 'Selected', reason: 'Shortlisted for the first development trial; verify suitability with sample checks.' }; next.bom = [{ id: uid(), materialId: material.id, quantity: 1.8, wastage: 5, rate: material.price }]; }
            next.labour = 120; next.processing = 35; next.packaging = 20;
            const design = { id: uid(), name: `${work.name} technical sketch`, version: 'V1', reference: 'DEMO-DESIGN-001 · front / back drawing', notes: 'Initial panel layout. Illustrative file reference.', colour: '#334155' };
            next.designs = [design]; next.selectedDesign = design.id;
            next.discussions = [{ id: uid(), author: persona.roleName, body: 'Sample review: sleeve opening feels tight. Increase the measurement before the next trial.', reference: 'Sample V1 / sleeve measurement', owner: 'Development lead', due: work.due, resolved: false }];
            next.samples = [{ id: uid(), version: 1, status: 'Rework', measurements: 'Chest 104 cm; sleeve opening 20 cm. Illustrative measurements.', feedback: 'Increase sleeve opening to 22 cm and review the revised fit.', reference: 'DEMO-SAMPLE-001 · fitting photo reference', materials: material ? [material.id] : [], design: design.id, cost: rdCost(next), date: new Date().toISOString() }];
            next.trials = [{ id: uid(), name: 'Sleeve fit', expected: 'Comfortable movement; opening 22 cm', actual: 'Opening 20 cm; tight during movement', evidence: 'DEMO-FIT-001 · initial fitting notes', status: 'Rework', action: 'Create V2, revise the opening and repeat the fit review.' }];
        }
        update({ rd: next, materials: Array.from(new Set([...work.materials, ...Object.keys(next.decisions)])) });
    }
    function revise() {
        if (!rd || !editable) return;
        const previous = rd.samples.at(-1);
        save({ samples: [...rd.samples, { id: uid(), version: (previous?.version || 0) + 1, status: 'Requested', measurements: previous?.measurements || '', feedback: '', reference: '', materials: selectedMaterials, design: rd.selectedDesign, cost, date: new Date().toISOString() }] });
    }
    return <div className="space-y-5">
        <div className="rounded-xl border border-violet-200 bg-violet-50 p-5 dark:border-violet-900 dark:bg-violet-950/30"><div className="flex items-center gap-2 text-violet-700 dark:text-violet-300"><FlaskConical className="h-5 w-5"/><strong>From brief to presentation-ready sample</strong></div><p className="mt-2 text-sm text-muted-foreground">Compare materials → develop designs → review samples → validate cost → hand over to Processing.</p></div>
        <div className="flex flex-wrap items-end gap-3"><div className="min-w-0 flex-1"><Field label="Client product"><select aria-label="R&D product" className={selectClass} value={work?.id || ''} onChange={e => { const next = products.find(w => w.id === e.target.value); if (next) onSelect(next); }}>{!products.length && <option value="">No products have entered R&D in this scope</option>}{products.map(w => <option key={w.id} value={w.id}>{data.clients.find(c => c.id === w.clientId)?.name} · {w.name} · {lifecycle[w.stage].name}</option>)}</select></Field></div>{work && <Button asChild variant="outline"><Link href={`/plm/clients?work=${encodeURIComponent(work.id)}`}>Full product lifecycle <ArrowRight className="ml-2 h-4 w-4"/></Link></Button>}</div>
        {!work ? <Panel title="No R&D products in this scope" hint="Complete Derivatives in Client PLM to bring a product into development."><Button asChild variant="outline"><Link href="/plm/clients">Open Client PLM</Link></Button></Panel> : !rd ? <Panel title={`Develop ${work.name}`} hint="Start a structured workspace or load an illustrative V1 rework scenario. Existing lifecycle notes and linked libraries are preserved."><div className="flex flex-wrap gap-3"><Button disabled={!editable} onClick={() => start(false)}>Start development</Button><Button disabled={!editable} variant="outline" onClick={() => start(true)}>Load illustrative V1 scenario</Button></div>{!editable && <p className="text-sm text-muted-foreground">Development can be started while the product is in R&D by Management, Admin or Sales.</p>}</Panel> : <>
            <div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{[['Responsible owner', work.owner || 'Development lead'], ['Sample deadline', rd.deadline || 'Set in Brief'], ['Current sample', rd.samples.length ? `V${rd.samples.at(-1)!.version} · ${rd.samples.at(-1)!.status}` : 'Not created'], ['Estimated / target', `${money(cost)} / ${money(rd.target)}`]].map(([label, value]) => <div key={label} className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-sm font-semibold">{value}</p></div>)}</div>
            {!editable && <p role="status" className="rounded-lg border p-3 text-sm">Read-only: {work.stage !== 1 ? `this product is now in ${lifecycle[work.stage].name}.` : 'choose Management, Admin or Sales to edit development.'}</p>}
            <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="min-w-0 space-y-4"><nav aria-label="R&D sections" className="flex flex-wrap gap-2">{tabs.map(name => <Button key={name} variant={tab === name ? 'default' : 'outline'} aria-pressed={tab === name} onClick={() => setTab(name)}>{name}</Button>)}</nav>
            <fieldset disabled={!editable} className="min-w-0 space-y-4">
            {tab === 'Brief' && <Panel title="Development brief" hint="Carry the client intent into measurable development targets."><div className="rounded-lg bg-muted/40 p-3 text-sm"><strong>Derivatives source</strong>{['Spec Sheet', 'Inspirations', 'Data Pool'].map((label, i) => <p key={label} className="mt-2"><span className="text-muted-foreground">{label}: </span>{work.evidence[`0:${i}`] || 'No source evidence recorded'}</p>)}</div><Field label="Client requirements / intended use"><Textarea rows={4} value={rd.brief} onChange={e => save({ brief: e.target.value })}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Size range"><Input value={rd.sizes} onChange={e => save({ sizes: e.target.value })}/></Field><Field label="Colourways"><Input value={rd.colours} onChange={e => save({ colours: e.target.value })}/></Field><NumberField label="Target unit cost (INR)" value={rd.target} onChange={target => save({ target })}/><Field label="Sample deadline"><Input type="date" value={rd.deadline} onChange={e => save({ deadline: e.target.value })}/></Field><Field label="Responsible owner"><Input value={work.owner || ''} onChange={e => update({ owner: e.target.value })}/></Field><Field label="Blocker / hold reason"><Input value={work.blocker || ''} onChange={e => update({ blocker: e.target.value })}/></Field></div></Panel>}
            {tab === 'References' && <>
                <Panel title="Material comparison" hint="Shortlist materials, compare specifications and record the selection decision."><Input aria-label="Search R&D materials" placeholder="Search material, supplier or composition…" value={search} onChange={e => setSearch(e.target.value)}/><select aria-label="Shortlist a material" className={selectClass} value="" onChange={e => { if (e.target.value) save({ decisions: { ...rd.decisions, [e.target.value]: { status: 'Shortlisted', reason: '' } } }); }}><option value="">Add material to comparison…</option>{data.materials.filter(m => !rd.decisions[m.id] && `${m.name} ${m.code} ${m.composition} ${m.supplier}`.toLowerCase().includes(search.toLowerCase())).map(m => <option key={m.id} value={m.id}>{m.code} · {m.name}</option>)}</select><div className="grid gap-4 md:grid-cols-2">{Object.entries(rd.decisions).map(([id, decision]) => { const m = data.materials.find(m => m.id === id); return <article key={id} className="space-y-3 rounded-lg border p-4"><h3 className="font-semibold">{m?.name || 'Missing library material'}</h3><p className="text-xs text-muted-foreground">{m?.code} · {m?.supplier}</p><p className="text-sm">{m?.composition}<br/>{m?.specification}</p><div className="rounded-md bg-muted/40 p-3 text-sm">{money(m?.price || 0)} / {m?.unit} · {m?.lead} days<br/>MOQ {m?.moq} · {m?.status}</div><Field label="Selection"><select className={selectClass} value={decision.status} onChange={e => { const decisions = { ...rd.decisions, [id]: { ...decision, status: e.target.value } }; update({ rd: { ...rd, decisions }, materials: Array.from(new Set([...work.materials.filter(mid => !rd.decisions[mid]), ...Object.entries(decisions).filter(([, d]) => d.status === 'Selected').map(([mid]) => mid)])) }); }}>{['Shortlisted', 'Selected', 'Rejected'].map(s => <option key={s}>{s}</option>)}</select></Field><Field label="Selection / rejection reason"><Textarea value={decision.reason} onChange={e => save({ decisions: { ...rd.decisions, [id]: { ...decision, reason: e.target.value } } })}/></Field></article>; })}</div></Panel>
                <Panel title="Product Library references" hint="Link existing products and samples as development references."><select aria-label="Add R&D reference sample" className={selectClass} value="" onChange={e => { if (e.target.value) update({ sampleIds: [...(work.sampleIds || []), e.target.value] }); }}><option value="">Link a reference sample…</option>{data.samples.filter(s => !work.sampleIds?.includes(s.id)).map(s => <option key={s.id} value={s.id}>{s.code} · {s.name} · {s.category}</option>)}</select>{work.sampleIds?.map(id => { const s = data.samples.find(s => s.id === id); return <div key={id} className="flex items-start justify-between gap-3 rounded-lg border p-3"><div><p className="text-sm font-semibold">{s?.name} · {s?.category}</p><p className="mt-1 text-xs text-muted-foreground">{s?.specification}</p></div><Button size="sm" variant="ghost" onClick={() => update({ sampleIds: work.sampleIds?.filter(sid => sid !== id) })}>Unlink</Button></div>; })}</Panel>
            </>}
            {tab === 'Discussions' && <Panel title="Decisions & action owners" hint="Connect feedback to a design or sample, assign an owner, and close the action when resolved."><Button variant="outline" onClick={() => save({ discussions: [...rd.discussions, { id: uid(), author: persona.roleName, body: '', reference: '', owner: '', due: rd.deadline, resolved: false }] })}><Plus className="mr-2 h-4 w-4"/>Add discussion</Button>{rd.discussions.map(item => { const change = (patch: Partial<typeof item>) => save({ discussions: rd.discussions.map(d => d.id === item.id ? { ...d, ...patch } : d) }); return <article key={item.id} className="space-y-3 rounded-lg border p-4"><p className="text-xs text-muted-foreground">Recorded by {item.author}</p><Field label="Discussion / decision"><Textarea value={item.body} onChange={e => change({ body: e.target.value, resolved: false })}/></Field><Field label="Related sample / design reference"><Input value={item.reference} onChange={e => change({ reference: e.target.value })}/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Action owner"><Input value={item.owner} onChange={e => change({ owner: e.target.value, resolved: false })}/></Field><Field label="Action due date"><Input type="date" value={item.due} onChange={e => change({ due: e.target.value })}/></Field></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={item.resolved} disabled={!item.body.trim() || !item.owner.trim() || !item.due} onChange={e => change({ resolved: e.target.checked })}/>Action resolved / decision recorded</label></article>; })}</Panel>}
            {tab === 'Designs' && <Panel title="Designs & file inventory" hint="Track design versions and references. File references are recorded here; binary uploads are not connected."><Button variant="outline" onClick={() => save({ designs: [...rd.designs, { id: uid(), name: work.name, version: `V${rd.designs.length + 1}`, reference: '', notes: '', colour: '#334155' }] })}><Plus className="mr-2 h-4 w-4"/>Add design version</Button>{rd.designs.map(item => { const change = (patch: Partial<typeof item>) => save({ designs: rd.designs.map(d => d.id === item.id ? { ...d, ...patch } : d) }); return <article key={item.id} className="grid gap-4 rounded-lg border p-4 sm:grid-cols-[120px_1fr]"><div><div className="flex h-32 items-center justify-center rounded-lg border" style={{ backgroundColor: item.colour }}><span className="rounded bg-white px-2 py-1 text-xs text-black">{item.version}</span></div><p className="mt-2 text-xs text-muted-foreground">Colourway swatch</p></div><div className="space-y-3"><Field label="Design title"><Input value={item.name} onChange={e => change({ name: e.target.value })}/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Version"><Input value={item.version} onChange={e => change({ version: e.target.value })}/></Field><Field label="Colourway swatch"><Input type="color" value={item.colour} onChange={e => change({ colour: e.target.value })}/></Field></div><Field label="Drawing / artwork / measurement sheet reference"><Input value={item.reference} onChange={e => change({ reference: e.target.value })}/></Field><Field label="Revision notes"><Textarea value={item.notes} onChange={e => change({ notes: e.target.value })}/></Field><label className="flex items-center gap-2 text-sm"><input type="radio" name="selected-design" checked={rd.selectedDesign === item.id} onChange={() => save({ selectedDesign: item.id })}/>Current selected design</label></div></article>; })}</Panel>}
            {tab === 'Samples' && <Panel title="Sample development & revisions" hint="New revisions preserve earlier measurements, feedback and cost snapshots. Update BOM and design selection before creating the next revision."><div className="flex flex-wrap gap-2">{rdSampleStatuses.map(s => <span key={s} className={`rounded-full border px-3 py-1 text-xs ${rd.samples.at(-1)?.status === s ? 'border-violet-500 bg-violet-50 text-violet-800 dark:bg-violet-950 dark:text-violet-200' : ''}`}>{s}</span>)}</div><Button variant="outline" onClick={revise}><Plus className="mr-2 h-4 w-4"/>{rd.samples.length ? 'Create next revision' : 'Create Sample V1'}</Button>{[...rd.samples].reverse().map((item, index) => { const change = (patch: Partial<typeof item>) => save({ samples: rd.samples.map(s => s.id === item.id ? { ...s, ...patch } : s) }); return <fieldset disabled={index !== 0} key={item.id} className="space-y-3 rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">Sample V{item.version} · {index === 0 ? 'Current revision' : 'Previous revision · preserved'}</h3><span className="text-sm">{money(item.cost)} / unit</span></div><p className="break-all text-xs text-muted-foreground">ID {item.id} · {new Date(item.date).toLocaleDateString('en-IN')}</p><p className="text-xs text-muted-foreground">Design: {rd.designs.find(d => d.id === item.design)?.version || 'None'} · Materials: {item.materials.map(id => data.materials.find(m => m.id === id)?.code || id).join(', ') || 'None'}</p><Field label="Sample status"><select className={selectClass} value={item.status} onChange={e => change({ status: e.target.value })}>{rdSampleStatuses.map(s => <option key={s}>{s}</option>)}</select></Field><Field label="Measurements / fit observations"><Textarea value={item.measurements} onChange={e => change({ measurements: e.target.value })}/></Field><Field label="Review feedback / changes from previous revision"><Textarea value={item.feedback} onChange={e => change({ feedback: e.target.value })}/></Field><Field label="Photo / sample file reference"><Input value={item.reference} onChange={e => change({ reference: e.target.value })}/></Field></fieldset>; })}</Panel>}
            {tab === 'BOM & costing' && <Panel title="Trial BOM & estimated unit cost" hint="Consumption is per finished unit, using each material’s library unit. Costs are illustrative INR estimates."><Button variant="outline" onClick={() => save({ bom: [...rd.bom, { id: uid(), materialId: '', quantity: 1, wastage: 0, rate: 0 }] })}><Plus className="mr-2 h-4 w-4"/>Add BOM row</Button>{rd.bom.map(row => { const change = (patch: Partial<typeof row>) => save({ bom: rd.bom.map(b => b.id === row.id ? { ...b, ...patch } : b) }); const material = data.materials.find(m => m.id === row.materialId); return <div key={row.id} className="space-y-3 rounded-lg border p-4"><Field label="Material"><select className={selectClass} value={row.materialId} onChange={e => { const m = data.materials.find(m => m.id === e.target.value); change({ materialId: e.target.value, rate: m?.price || 0 }); }}><option value="">Choose material…</option>{data.materials.map(m => <option key={m.id} value={m.id}>{m.code} · {m.name}</option>)}</select></Field><div className="grid gap-3 sm:grid-cols-3"><NumberField label={`Consumption (${material?.unit || 'units'})`} value={row.quantity} onChange={quantity => change({ quantity })}/><NumberField label="Wastage (%)" value={row.wastage} max={100} onChange={wastage => change({ wastage })}/><NumberField label={`Rate (INR / ${material?.unit || 'unit'})`} value={row.rate} onChange={rate => change({ rate })}/></div><div className="flex items-center justify-between"><p className="text-sm font-semibold">Line cost {money(row.quantity * (1 + row.wastage / 100) * row.rate)}</p><Button size="sm" variant="ghost" onClick={() => save({ bom: rd.bom.filter(b => b.id !== row.id) })}>Remove row</Button></div></div>; })}<div className="grid gap-3 sm:grid-cols-3"><NumberField label="Labour / unit (INR)" value={rd.labour} onChange={labour => save({ labour })}/><NumberField label="Processing / unit (INR)" value={rd.processing} onChange={processing => save({ processing })}/><NumberField label="Packaging / unit (INR)" value={rd.packaging} onChange={packaging => save({ packaging })}/></div><div className="rounded-lg bg-muted/40 p-4"><p className="font-semibold">Estimated unit cost: {money(cost)}</p><p className={`mt-1 text-sm ${cost > rd.target ? 'text-amber-700 dark:text-amber-300' : 'text-emerald-700 dark:text-emerald-300'}`}>{money(Math.abs(cost - rd.target))} {cost > rd.target ? 'above' : 'below'} target · Order estimate {money(cost * work.quantity)} for {work.quantity} units</p></div><Field label="Cost variance explanation / decision"><Textarea value={rd.costNote} onChange={e => save({ costNote: e.target.value })}/></Field></Panel>}
            {tab === 'Development checks' && <Panel title="Development checks" hint="Record trial observations and evidence. Formal CQP sign-off remains in Product Evaluation."><Button variant="outline" onClick={() => save({ trials: [...rd.trials, { id: uid(), name: '', expected: '', actual: '', evidence: '', status: 'Pending', action: '' }] })}><Plus className="mr-2 h-4 w-4"/>Add check</Button>{rd.trials.map(item => { const change = (patch: Partial<typeof item>) => save({ trials: rd.trials.map(t => t.id === item.id ? { ...t, ...patch } : t) }); return <article key={item.id} className="space-y-3 rounded-lg border p-4"><Field label="Check name (fit, shrinkage, seam, colour…)"><Input value={item.name} onChange={e => change({ name: e.target.value })}/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Expected result"><Textarea value={item.expected} onChange={e => change({ expected: e.target.value })}/></Field><Field label="Actual result"><Textarea value={item.actual} onChange={e => change({ actual: e.target.value })}/></Field></div><Field label="Evidence / test reference"><Input value={item.evidence} onChange={e => change({ evidence: e.target.value })}/></Field><Field label="Result"><select className={selectClass} value={item.status} onChange={e => change({ status: e.target.value })}>{['Pending', 'Pass', 'Rework', 'Fail'].map(s => <option key={s}>{s}</option>)}</select></Field><Field label="Follow-up / resolution"><Textarea value={item.action} onChange={e => change({ action: e.target.value })}/></Field></article>; })}</Panel>}
            </fieldset></div><aside className="space-y-4 xl:sticky xl:top-4"><Panel title="Processing handover" hint="Client approval happens in the next stage."><div className="flex items-center gap-2 text-sm font-semibold"><CheckCircle2 className="h-4 w-4"/>{issues.length ? `${issues.length} items to resolve` : 'Development package ready'}</div>{issues.length > 0 && <ul className="list-disc space-y-3 pl-4 text-xs text-muted-foreground">{issues.map(issue => <li key={issue}>{issue}</li>)}</ul>}<Button className="w-full" disabled={!editable || !!issues.length} onClick={() => { if (!work) return; const next = rdHandover(work); if (next !== work) update(next); }}>Hand over to Processing<ArrowRight className="ml-2 h-4 w-4"/></Button><p className="text-xs text-muted-foreground">Handover records evidence for all five R&D tasks and preserves this workspace for review.</p></Panel><p className="px-1 text-xs text-muted-foreground">Changes save in this browser. Illustrative supplier prices and file references support the demo.</p></aside></div>
        </>}
    </div>;
}
