export interface ModuleNode {
  id: string;
  name: string;
  shortName: string;
  number: number;
  category: "master" | "transaction" | "control" | "report" | "integration";
  route: string;
  icon: string;
  description: string;
  responsibilities: string[];
  ownerRoles: string[];
  upstream: string[];
  downstream: string[];
  kpis: { label: string; value: string }[];
  goldenStep?: number;
  x: number;
  y: number;
}

export interface ModuleEdge {
  from: string;
  to: string;
  label: string;
  entityOrEvent: string;
  workflowIds: string[];
}

export const MODULES: ModuleNode[] = [
  {
    id: "identity-access",
    name: "Identity, Access & Approvals",
    shortName: "Identity & Access",
    number: 1,
    category: "control",
    route: "/admin/approvals",
    icon: "ShieldCheck",
    description: "Multi-level maker-checker approvals, role-based access, segregation of duties, and audit logs.",
    responsibilities: [
      "User authentication and multi-factor session validation",
      "Role and location-scoped authorization",
      "Multi-level approval queues and maker-checker validation",
      "Immutable audit log records with diffs",
    ],
    ownerRoles: ["ADMIN", "MANAGEMENT"],
    upstream: [],
    downstream: [
      "master-data", "sales-orders", "procurement", "production-execution", "finance-costing"
    ],
    kpis: [
      { label: "Pending Approvals", value: "3" },
      { label: "Active Roles", value: "10" },
      { label: "Audit Entries", value: "248" },
    ],
    x: 80,
    y: 80,
  },
  {
    id: "organization-locations",
    name: "Organization & Locations",
    shortName: "Org & Locations",
    number: 2,
    category: "master",
    route: "/masters",
    icon: "Building2",
    description: "Companies, business units, factories, warehouses, Tirupur atelier, and field offices.",
    responsibilities: [
      "Multi-entity hierarchy (INNOTEX HQ, 4 Business Units)",
      "Manufacturing centres: Tirupur Garment, Coimbatore Garment, Kinathukidavu Composites",
      "Warehouse and location scoping for operators",
      "Job-worker location mapping",
    ],
    ownerRoles: ["ADMIN", "MANAGEMENT"],
    upstream: ["identity-access"],
    downstream: ["master-data", "inventory-traceability", "production-execution"],
    kpis: [
      { label: "Business Units", value: "4" },
      { label: "Operating Locations", value: "10" },
      { label: "Warehouses", value: "4" },
    ],
    x: 80,
    y: 220,
  },
  {
    id: "master-data",
    name: "Master Data Management",
    shortName: "Master Data",
    number: 3,
    category: "master",
    route: "/masters",
    icon: "Database",
    description: "Centralized catalogue of customers, suppliers, fabrics, trims, UOMs, GST rates, and machines.",
    responsibilities: [
      "Customer and Supplier registers with GSTIN and tax states",
      "Item Master with automatic/manual code generation",
      "Fabric-specific profiles (knit/weave, composition, GSM, vendor)",
      "Customer item code aliasing (e.g. APX-TRJ-NVY -> SP-JKT-APX-01)",
    ],
    ownerRoles: ["ADMIN", "SALES", "PURCHASE", "STORE"],
    upstream: ["organization-locations"],
    downstream: [
      "plm-sampling", "sales-orders", "procurement", "bom-mrp", "production-execution"
    ],
    kpis: [
      { label: "Item Catalogue", value: "128" },
      { label: "Customers", value: "16" },
      { label: "Vendors", value: "24" },
    ],
    x: 80,
    y: 360,
  },
  {
    id: "plm-sampling",
    name: "Product Lifecycle & Sampling (PLM)",
    shortName: "PLM & Sampling",
    number: 4,
    category: "transaction",
    route: "/plm/designs",
    icon: "Sparkles",
    description: "Design briefs, product specifications, sample iterations, and mandatory bulk release gates.",
    responsibilities: [
      "Design brief registration with season and artwork attachments",
      "Product specification revisions and customer requirement tracking",
      "Sample iterations at Tirupur Atelier with QC results",
      "Customer approval gate before bulk sales order release",
    ],
    ownerRoles: ["SALES", "MANAGEMENT", "QUALITY"],
    upstream: ["master-data"],
    downstream: ["sales-orders", "bom-mrp", "quality-management"],
    kpis: [
      { label: "Active Briefs", value: "6" },
      { label: "Approved Samples", value: "12" },
      { label: "Bulk Released", value: "9" },
    ],
    goldenStep: 1,
    x: 280,
    y: 80,
  },
  {
    id: "sales-orders",
    name: "Sales & Customer Orders",
    shortName: "Sales Orders",
    number: 5,
    category: "transaction",
    route: "/sales/orders/a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d",
    icon: "ShoppingCart",
    description: "Customer enquiries, itemized quotations, size-wise variant sales orders, and order confirmation.",
    responsibilities: [
      "Enquiry to Quotation workflow with price list mapping",
      "Multi-variant size matrix booking (Navy / S, M, L, XL)",
      "Binding approved spec revisions and BOM revisions",
      "Order confirmation triggering material planning",
    ],
    ownerRoles: ["SALES", "MANAGEMENT"],
    upstream: ["plm-sampling", "master-data"],
    downstream: ["bom-mrp", "production-execution", "dispatch-logistics", "finance-costing"],
    kpis: [
      { label: "Active Orders", value: "14" },
      { label: "Order Book", value: "₹48.2L" },
      { label: "Apex Order Qty", value: "1,100 pcs" },
    ],
    goldenStep: 2,
    x: 280,
    y: 220,
  },
  {
    id: "bom-mrp",
    name: "BOM, Revision & MRP",
    shortName: "BOM & MRP",
    number: 9,
    category: "transaction",
    route: "/manufacturing/plans",
    icon: "Layers",
    description: "Revisioned multi-level BOMs, wastage calculations, substitute items, and shortage MRP explosion.",
    responsibilities: [
      "Standard and customer-specific BOMs with revision history",
      "Planned cutting/processing wastage % and substitute materials",
      "MRP net shortage calculation against ledger stock and reservations",
      "Automated Purchase Requisition generation from shortages",
    ],
    ownerRoles: ["PRODUCTION", "QUALITY", "MANAGEMENT"],
    upstream: ["sales-orders", "master-data", "inventory-traceability"],
    downstream: ["procurement", "production-execution", "finance-costing"],
    kpis: [
      { label: "Released BOMs", value: "28" },
      { label: "MRP Shortages", value: "2" },
      { label: "BOM Revisions", value: "v2 Active" },
    ],
    goldenStep: 3,
    x: 480,
    y: 220,
  },
  {
    id: "procurement",
    name: "Procurement & Sourcing",
    shortName: "Procurement",
    number: 6,
    category: "transaction",
    route: "/procurement/requisitions",
    icon: "Truck",
    description: "Purchase requisitions, RFQs, supplier quotation comparison, and threshold-controlled POs.",
    responsibilities: [
      "Shortage-driven Purchase Requisitions",
      "RFQ floatation and multi-vendor rate comparisons",
      "Purchase Order generation with tax codes and terms",
      "Maker-checker threshold approvals for large orders",
    ],
    ownerRoles: ["PURCHASE", "MANAGEMENT"],
    upstream: ["bom-mrp", "master-data"],
    downstream: ["inward-grn", "finance-costing"],
    kpis: [
      { label: "Open POs", value: "5" },
      { label: "Pending PRs", value: "2" },
      { label: "PO Total Value", value: "₹18.4L" },
    ],
    goldenStep: 4,
    x: 680,
    y: 80,
  },
  {
    id: "inward-grn",
    name: "Inward & GRN Verification",
    shortName: "Inward & GRN",
    number: 7,
    category: "transaction",
    route: "/procurement/receipts/grn-apex-01",
    icon: "PackageCheck",
    description: "Gate entry, supplier delivery challan check, GRN, and incoming fabric lot disposition split.",
    responsibilities: [
      "Gate entry logging with vehicle and LR number",
      "GRN verification against Purchase Order lines",
      "Incoming fabric QC split: Accepted, Hold, and Rejected quantities",
      "Supplier lot and shade code capture",
    ],
    ownerRoles: ["STORE", "QUALITY"],
    upstream: ["procurement"],
    downstream: ["inventory-traceability", "quality-management", "finance-costing"],
    kpis: [
      { label: "Today Inward", value: "3 GRNs" },
      { label: "Passed Lots", value: "85%" },
      { label: "Quarantine Hold", value: "15%" },
    ],
    goldenStep: 5,
    x: 680,
    y: 220,
  },
  {
    id: "inventory-traceability",
    name: "Inventory & Textile Traceability",
    shortName: "Inventory & Rolls",
    number: 8,
    category: "transaction",
    route: "/inventory/stock",
    icon: "Boxes",
    description: "Append-only stock ledgers, warehouse bins, and complete fabric roll genealogy.",
    responsibilities: [
      "Multi-status stock tracking (Available, Reserved, Hold, Rejected)",
      "Fabric roll genealogy: Roll #, Supplier Lot, Batch, Shade, Vendor",
      "Remaining roll quantity derived from ledger movements",
      "Stock reservation against confirmed production orders",
    ],
    ownerRoles: ["STORE", "PRODUCTION"],
    upstream: ["inward-grn", "production-execution"],
    downstream: ["bom-mrp", "production-execution", "dispatch-logistics"],
    kpis: [
      { label: "Active Rolls", value: "48" },
      { label: "Stock Value", value: "₹34.8L" },
      { label: "Quarantine Rolls", value: "2" },
    ],
    goldenStep: 6,
    x: 680,
    y: 360,
  },
  {
    id: "production-execution",
    name: "Production Planning & Execution",
    shortName: "Production",
    number: 10,
    category: "transaction",
    route: "/manufacturing/orders/d1e2f3a4-b5c6-7d8e-9f0a-1b2c3d4e5f6a",
    icon: "Cpu",
    description: "Shopfloor scheduling and 7-stage card execution from cutting to finished packing.",
    responsibilities: [
      "Production Order release and raw material issues",
      "Execution stages: Cutting, Stitching, Printing, Washing, Finishing, QC, Packing",
      "Input, Good, Scrap, and Rework reconciliation at each operation",
      "Finished goods receipt generation upon final stage QC pass",
    ],
    ownerRoles: ["PRODUCTION", "OPERATOR", "QUALITY"],
    upstream: ["bom-mrp", "sales-orders", "inventory-traceability"],
    downstream: ["inventory-traceability", "quality-management", "finance-costing", "job-work"],
    kpis: [
      { label: "Active Orders", value: "8" },
      { label: "Daily Output", value: "420 pcs" },
      { label: "WIP Stages", value: "7 Stages" },
    ],
    goldenStep: 7,
    x: 480,
    y: 360,
  },
  {
    id: "job-work",
    name: "Job Work & Subcontracting",
    shortName: "Job Work",
    number: 11,
    category: "transaction",
    route: "/job-work/orders/jw-emb-01",
    icon: "Scissors",
    description: "Outsourced processing (embroidery, dyeing), material issue challans, and stock reconciliation.",
    responsibilities: [
      "Job-work order contracts with agreed rates and operations",
      "Material issue challan and tracking stock at subcontractor site",
      "Job-work receipt, defect logging, and scrap reconciliation",
      "Service quantity matching against vendor invoices",
    ],
    ownerRoles: ["PRODUCTION", "STORE", "QUALITY", "FINANCE"],
    upstream: ["production-execution", "inventory-traceability"],
    downstream: ["quality-management", "inventory-traceability", "finance-costing"],
    kpis: [
      { label: "Active Subcontracts", value: "3" },
      { label: "Stock at Workers", value: "₹4.2L" },
      { label: "Reconciled Rate", value: "100%" },
    ],
    x: 480,
    y: 500,
  },
  {
    id: "quality-management",
    name: "Quality Management & Inspection",
    shortName: "Quality Assurance",
    number: 12,
    category: "control",
    route: "/quality/inspections/qi-fabric-01",
    icon: "CheckCircle2",
    description: "Customer-specific parameter checklists, Pass/Fail/Hold disposition, and test certificates.",
    responsibilities: [
      "Incoming fabric roll inspection and GSM/shade tolerance check",
      "In-process stage quality gates and rework order routing",
      "Finished goods final inspection release before dispatch",
      "Customer compliance certificate generation",
    ],
    ownerRoles: ["QUALITY", "MANAGEMENT"],
    upstream: ["inward-grn", "production-execution", "job-work"],
    downstream: ["inventory-traceability", "dispatch-logistics"],
    kpis: [
      { label: "First Pass Yield", value: "96.4%" },
      { label: "Active Inspections", value: "4" },
      { label: "Rework Orders", value: "1" },
    ],
    goldenStep: 8,
    x: 280,
    y: 360,
  },
  {
    id: "dispatch-logistics",
    name: "Dispatch & Logistics",
    shortName: "Dispatch",
    number: 13,
    category: "transaction",
    route: "/dispatch/plans/dp-apex-01",
    icon: "Send",
    description: "Pick/packing lists, partial shipments, delivery challans, transporter LR, and signed PODs.",
    responsibilities: [
      "Finished goods stock allocation against open order quantities",
      "Carton packing lists and barcode shipping labels",
      "Partial shipment handling (Shipment 1 & 2) without premature order closure",
      "Delivery Challan (DC) and Proof of Delivery (POD) image capture",
    ],
    ownerRoles: ["DISPATCH", "SALES"],
    upstream: ["sales-orders", "inventory-traceability", "quality-management"],
    downstream: ["finance-costing"],
    kpis: [
      { label: "Shipments Today", value: "2" },
      { label: "On-Time Dispatch", value: "98%" },
      { label: "Pending PODs", value: "0" },
    ],
    goldenStep: 9,
    x: 280,
    y: 500,
  },
  {
    id: "finance-costing",
    name: "Invoicing, Finance & Costing",
    shortName: "Finance & Costing",
    number: 14,
    category: "transaction",
    route: "/finance/profitability",
    icon: "Receipt",
    description: "Tax invoices with GST breakdown, payment receipts, and 9-component profitability waterfall.",
    responsibilities: [
      "Tax invoice generation from delivery challans with GST breakdown",
      "Customer payment entries and outstanding balance updates",
      "9-part cost waterfall: Raw material, processing, labour, machine, job work, packaging, freight, overhead, wastage",
      "Profitability analysis by Sales Order, Product, and Customer",
    ],
    ownerRoles: ["FINANCE", "MANAGEMENT"],
    upstream: ["dispatch-logistics", "production-execution", "procurement"],
    downstream: ["reports-dashboard", "integrations-documents"],
    kpis: [
      { label: "Invoiced Total", value: "₹30.2L" },
      { label: "Gross Margin", value: "28.4%" },
      { label: "Outstanding Rec.", value: "₹5.8L" },
    ],
    goldenStep: 10,
    x: 80,
    y: 500,
  },
  {
    id: "reports-dashboard",
    name: "Reports & Executive Dashboard",
    shortName: "Executive Dashboard",
    number: 15,
    category: "report",
    route: "/dashboard",
    icon: "BarChart3",
    description: "Executive KPIs, Golden Scenario tracker, WIP stage overview, and CSV exportable registers.",
    responsibilities: [
      "Executive overview: Revenue, WIP, QC passes, and pending approvals",
      "Golden Scenario 10-stage lifecycle progress tracker",
      "Attention Queue for urgent shortage and quarantine items",
      "Exportable registers: Sales, Purchase, Stock Ageing, GST, Profitability",
    ],
    ownerRoles: ["MANAGEMENT", "ADMIN", "SALES", "PRODUCTION"],
    upstream: [
      "sales-orders", "procurement", "inventory-traceability", "production-execution", "finance-costing"
    ],
    downstream: [],
    kpis: [
      { label: "Live Dashboards", value: "6" },
      { label: "Exportable Reports", value: "9" },
      { label: "System Health", value: "Optimal" },
    ],
    x: 80,
    y: 640,
  },
  {
    id: "integrations-documents",
    name: "Integrations & Documents Hub",
    shortName: "Integrations Hub",
    number: 16,
    category: "integration",
    route: "/integrations",
    icon: "PlugZap",
    description: "15 simulated adapters (E-Invoice, E-Way Bill, GST, Tally, Portals, IoT) and audit event logs.",
    responsibilities: [
      "15 simulated adapter cards with mode indicator ('mock')",
      "Payload inspection drawer and deterministic mock latency",
      "Idempotent event retry and transmission audit logging",
      "Document attachments linked via Supabase Storage ('erp-documents')",
    ],
    ownerRoles: ["ADMIN", "MANAGEMENT", "FINANCE"],
    upstream: ["finance-costing", "dispatch-logistics"],
    downstream: [],
    kpis: [
      { label: "Connected Adapters", value: "15" },
      { label: "Simulated Events", value: "48" },
      { label: "Retry Success Rate", value: "100%" },
    ],
    x: 280,
    y: 640,
  },
];

export const MODULE_EDGES: ModuleEdge[] = [
  {
    from: "identity-access",
    to: "master-data",
    label: "Role scopes & permissions",
    entityOrEvent: "user_location_scopes",
    workflowIds: ["all"],
  },
  {
    from: "organization-locations",
    to: "master-data",
    label: "Facility & warehouse master",
    entityOrEvent: "locations",
    workflowIds: ["all"],
  },
  {
    from: "master-data",
    to: "plm-sampling",
    label: "Items & fabric specifications",
    entityOrEvent: "items -> design_briefs",
    workflowIds: ["workflow-a"],
  },
  {
    from: "plm-sampling",
    to: "sales-orders",
    label: "Approved sample & spec release",
    entityOrEvent: "specification_revisions (Bulk Released)",
    workflowIds: ["workflow-a", "golden-path"],
  },
  {
    from: "sales-orders",
    to: "bom-mrp",
    label: "Order lines & demand",
    entityOrEvent: "sales_orders (POSTED) -> MRP",
    workflowIds: ["workflow-b", "golden-path"],
  },
  {
    from: "bom-mrp",
    to: "procurement",
    label: "Component shortages",
    entityOrEvent: "material_plan_lines -> purchase_requisitions",
    workflowIds: ["workflow-b", "golden-path"],
  },
  {
    from: "procurement",
    to: "inward-grn",
    label: "Purchase Order supply",
    entityOrEvent: "purchase_orders -> gate_entries / grns",
    workflowIds: ["workflow-b", "golden-path"],
  },
  {
    from: "inward-grn",
    to: "quality-management",
    label: "Incoming fabric inspection",
    entityOrEvent: "grns -> quality_inspections (INCOMING)",
    workflowIds: ["workflow-b", "golden-path"],
  },
  {
    from: "inward-grn",
    to: "inventory-traceability",
    label: "Accepted fabric roll receipts",
    entityOrEvent: "fabric_rolls (Roll #, Lot, Shade)",
    workflowIds: ["workflow-b", "golden-path"],
  },
  {
    from: "inventory-traceability",
    to: "production-execution",
    label: "Material issue & reservations",
    entityOrEvent: "stock_reservations -> material_issues",
    workflowIds: ["workflow-b", "workflow-c", "golden-path"],
  },
  {
    from: "bom-mrp",
    to: "production-execution",
    label: "Production routing & stages",
    entityOrEvent: "boms -> production_orders",
    workflowIds: ["workflow-b", "workflow-c", "golden-path"],
  },
  {
    from: "production-execution",
    to: "job-work",
    label: "External process subcontract",
    entityOrEvent: "production_orders -> job_work_orders",
    workflowIds: ["workflow-d"],
  },
  {
    from: "job-work",
    to: "production-execution",
    label: "Reconciled subcontractor receipt",
    entityOrEvent: "job_work_receipts -> production_entries",
    workflowIds: ["workflow-d"],
  },
  {
    from: "production-execution",
    to: "quality-management",
    label: "Stage & finished goods QC",
    entityOrEvent: "production_operations -> quality_inspections",
    workflowIds: ["workflow-c", "golden-path"],
  },
  {
    from: "quality-management",
    to: "inventory-traceability",
    label: "Finished goods stock release",
    entityOrEvent: "finished_goods_receipts (Available Stock)",
    workflowIds: ["workflow-c", "golden-path"],
  },
  {
    from: "sales-orders",
    to: "dispatch-logistics",
    label: "Order delivery requirement",
    entityOrEvent: "sales_order_lines -> dispatch_plans",
    workflowIds: ["workflow-c", "golden-path"],
  },
  {
    from: "inventory-traceability",
    to: "dispatch-logistics",
    label: "Finished goods pick & pack",
    entityOrEvent: "dispatch_allocations (Pick/Pack list)",
    workflowIds: ["workflow-c", "golden-path"],
  },
  {
    from: "dispatch-logistics",
    to: "finance-costing",
    label: "Delivery Challan (DC) & POD",
    entityOrEvent: "delivery_challans -> sales_invoices",
    workflowIds: ["workflow-e", "golden-path"],
  },
  {
    from: "finance-costing",
    to: "integrations-documents",
    label: "E-Invoice / E-Way Bill / Tally sync",
    entityOrEvent: "sales_invoices -> integration_events",
    workflowIds: ["workflow-e", "golden-path"],
  },
  {
    from: "finance-costing",
    to: "reports-dashboard",
    label: "Cost waterfall & profitability",
    entityOrEvent: "cost_snapshots -> Executive Dashboard",
    workflowIds: ["workflow-e", "golden-path"],
  },
];
