export interface WorkflowStep {
  stepNumber: number;
  moduleId: string;
  moduleName: string;
  title: string;
  description: string;
  role: string;
  documentNumber: string;
  documentType: string;
  route: string;
  badge: string;
}

export interface WorkflowDefinition {
  id: string;
  name: string;
  shortDescription: string;
  roles: string[];
  steps: WorkflowStep[];
}

export const WORKFLOWS: Record<string, WorkflowDefinition> = {
  "golden-path": {
    id: "golden-path",
    name: "Golden Path: Enquiry to Cash",
    shortDescription: "Complete end-to-end lifecycle of the Custom Performance Training Jacket (SO-APX-2026-001) for Apex Endurance.",
    roles: ["Management", "Sales", "Production", "Purchase", "Store", "Quality", "Dispatch", "Finance"],
    steps: [
      {
        stepNumber: 1,
        moduleId: "plm-sampling",
        moduleName: "PLM & Sampling",
        title: "Approved Sample & Bulk Release",
        description: "Iteration 2 approved at Tirupur atelier; specification marked 'Released for Bulk' to unlock commercial order.",
        role: "Product Developer & Quality Lead",
        documentNumber: "SMP-APX-001 (Rev 2)",
        documentType: "SAMPLE_ITERATION",
        route: "/plm/designs",
        badge: "BULK RELEASED",
      },
      {
        stepNumber: 2,
        moduleId: "sales-orders",
        moduleName: "Sales & Customer Orders",
        title: "Confirmed Sales Order (1,100 pcs)",
        description: "Order SO-APX-2026-001 confirmed for 4 Navy sizes (S, M, L, XL), bound to customer spec and BOM revision 2.",
        role: "Sales Lead",
        documentNumber: "SO-APX-2026-001",
        documentType: "SALES_ORDER",
        route: "/sales/orders/a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d",
        badge: "POSTED",
      },
      {
        stepNumber: 3,
        moduleId: "bom-mrp",
        moduleName: "BOM & MRP Workbench",
        title: "BOM Explosion & MRP Shortage Calculation",
        description: "Exploded BOM v2 with 5% cutting wastage; identified shortage on Recycled Coil Zipper (TRM-ZIP-65).",
        role: "Production Planner",
        documentNumber: "MRP-SO-APX-2026-001",
        documentType: "MATERIAL_PLAN",
        route: "/manufacturing/plans",
        badge: "SHORTAGE FLAGGED",
      },
      {
        stepNumber: 4,
        moduleId: "procurement",
        moduleName: "Procurement & Sourcing",
        title: "Purchase Requisition & PO Issued",
        description: "Auto-generated PR converted to PO for 1,155 zippers; approved under maker-checker threshold.",
        role: "Purchase Manager",
        documentNumber: "PO-2026-042",
        documentType: "PURCHASE_ORDER",
        route: "/procurement/requisitions",
        badge: "APPROVED",
      },
      {
        stepNumber: 5,
        moduleId: "inward-grn",
        moduleName: "Inward & GRN Verification",
        title: "Material Inward & Incoming Fabric QC Split",
        description: "Fabric lot received; QC split into 2 Accepted rolls (800m), 1 Hold roll (200m) quarantined for shade variance.",
        role: "Store & Quality",
        documentNumber: "GRN-2026-088",
        documentType: "GRN",
        route: "/procurement/receipts/grn-apex-01",
        badge: "QC SPLIT APPLIED",
      },
      {
        stepNumber: 6,
        moduleId: "inventory-traceability",
        moduleName: "Inventory & Textile Traceability",
        title: "Fabric Roll Genealogy & Material Reservation",
        description: "Roll R-POLY-001 (Lot LOT-TEX-88, Shade NAVY-A) registered and reserved for Cutting floor.",
        role: "Store Manager",
        documentNumber: "R-POLY-001",
        documentType: "FABRIC_ROLL",
        route: "/inventory/rolls/80000000-0000-0000-0000-000000000001",
        badge: "RESERVED",
      },
      {
        stepNumber: 7,
        moduleId: "production-execution",
        moduleName: "Production Execution",
        title: "Shopfloor 7-Stage Execution",
        description: "Cutting -> Stitching -> Printing -> Finishing -> Pre-pack QC; recorded 4 pcs cutting scrap and 1 rework.",
        role: "Production Planner & Operator",
        documentNumber: "PRD-2026-101",
        documentType: "PRODUCTION_ORDER",
        route: "/manufacturing/orders/d1e2f3a4-b5c6-7d8e-9f0a-1b2c3d4e5f6a",
        badge: "RECONCILED",
      },
      {
        stepNumber: 8,
        moduleId: "quality-management",
        moduleName: "Quality Assurance",
        title: "Finished Goods Quality Release",
        description: "Customer parameter checklist verified (tensile, colorfastness, measurements); passed for dispatch release.",
        role: "Quality Assurance Lead",
        documentNumber: "QC-FG-2026-012",
        documentType: "QUALITY_INSPECTION",
        route: "/quality/inspections/qi-fabric-01",
        badge: "PASS - RELEASED",
      },
      {
        stepNumber: 9,
        moduleId: "dispatch-logistics",
        moduleName: "Dispatch & Logistics",
        title: "Partial Shipment & Delivery Challan with POD",
        description: "Shipment 1 dispatched (600 jackets) via SpotOn Logistics; LR number assigned and signed POD attached.",
        role: "Dispatch Lead",
        documentNumber: "DC-APX-01",
        documentType: "DELIVERY_CHALLAN",
        route: "/dispatch/plans/dp-apex-01",
        badge: "POD ATTACHED",
      },
      {
        stepNumber: 10,
        moduleId: "finance-costing",
        moduleName: "Finance & Costing",
        title: "Tax Invoice & 9-Part Cost Waterfall",
        description: "Tax invoice INV-APX-01 posted (₹16,50,000 + GST); cost waterfall demonstrates 28.4% gross margin.",
        role: "Finance Head & Executive",
        documentNumber: "INV-APX-01",
        documentType: "SALES_INVOICE",
        route: "/finance/profitability",
        badge: "MARGIN 28.4%",
      },
    ],
  },
  "workflow-a": {
    id: "workflow-a",
    name: "Workflow A: Design to Bulk Release",
    shortDescription: "Design brief creation, specification revisions, Tirupur sampling iterations, and bulk commercial release.",
    roles: ["Sales", "Product Developer", "Quality", "Management"],
    steps: [
      {
        stepNumber: 1,
        moduleId: "plm-sampling",
        moduleName: "PLM & Sampling",
        title: "Create Design Brief & Season Context",
        description: "Attach reference sketches and customer requirements for the new performance jacket.",
        role: "Sales / Product Developer",
        documentNumber: "BRF-2026-004",
        documentType: "DESIGN_BRIEF",
        route: "/plm/designs",
        badge: "SUBMITTED",
      },
      {
        stepNumber: 2,
        moduleId: "plm-sampling",
        moduleName: "PLM & Sampling",
        title: "Register Product Specifications",
        description: "Define fabric specs, colour swatches, tensile tolerances, and customer item codes.",
        role: "Product Developer",
        documentNumber: "SPC-APX-01 (Rev 1)",
        documentType: "SPECIFICATION",
        route: "/plm/designs",
        badge: "DRAFT",
      },
      {
        stepNumber: 3,
        moduleId: "plm-sampling",
        moduleName: "PLM & Sampling",
        title: "Sample Iteration 1 (Rejected with Feedback)",
        description: "First prototype stitched at Tirupur atelier; zipper tolerance rejected by customer QC.",
        role: "Tirupur Atelier Operator",
        documentNumber: "SMP-APX-001 (Rev 1)",
        documentType: "SAMPLE_ITERATION",
        route: "/plm/designs",
        badge: "REWORK NEEDED",
      },
      {
        stepNumber: 4,
        moduleId: "plm-sampling",
        moduleName: "PLM & Sampling",
        title: "Sample Iteration 2 (Approved & Bulk Released)",
        description: "Corrected zipper tape; customer approves sample; specification promoted to 'Released for Bulk'.",
        role: "Quality & Management",
        documentNumber: "SMP-APX-001 (Rev 2)",
        documentType: "SAMPLE_ITERATION",
        route: "/plm/designs",
        badge: "BULK RELEASED",
      },
    ],
  },
  "workflow-b": {
    id: "workflow-b",
    name: "Workflow B: Procure-to-Produce Make-to-Order",
    shortDescription: "Sales order confirmation, BOM resolution, MRP shortage calculation, purchase order, and GRN lot split.",
    roles: ["Sales", "Production", "Purchase", "Store", "Quality"],
    steps: [
      {
        stepNumber: 1,
        moduleId: "sales-orders",
        moduleName: "Sales & Customer Orders",
        title: "Confirm Sales Order",
        description: "Confirm commercial order against approved bulk specification.",
        role: "Sales Lead",
        documentNumber: "SO-APX-2026-001",
        documentType: "SALES_ORDER",
        route: "/sales/orders/a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d",
        badge: "CONFIRMED",
      },
      {
        stepNumber: 2,
        moduleId: "bom-mrp",
        moduleName: "BOM & MRP Workbench",
        title: "Run MRP & Net Shortages",
        description: "Explode requirements across 1,100 jackets with wastage and check current stock balances.",
        role: "Production Planner",
        documentNumber: "MRP-2026-001",
        documentType: "MATERIAL_PLAN",
        route: "/manufacturing/plans",
        badge: "CALCULATED",
      },
      {
        stepNumber: 3,
        moduleId: "procurement",
        moduleName: "Procurement & Sourcing",
        title: "Issue PO with Maker-Checker Approval",
        description: "Send Purchase Order to approved zipper supplier after manager check.",
        role: "Purchase Manager",
        documentNumber: "PO-2026-042",
        documentType: "PURCHASE_ORDER",
        route: "/procurement/requisitions",
        badge: "APPROVED",
      },
      {
        stepNumber: 4,
        moduleId: "inward-grn",
        moduleName: "Inward & GRN",
        title: "Gate Inward & Accepted/Hold Split",
        description: "Receive fabric rolls; split accepted vs quarantined rolls with lot and shade traceability.",
        role: "Store & Quality",
        documentNumber: "GRN-2026-088",
        documentType: "GRN",
        route: "/procurement/receipts/grn-apex-01",
        badge: "LOT RECORDED",
      },
    ],
  },
  "workflow-d": {
    id: "workflow-d",
    name: "Workflow D: Job Work & Subcontracting",
    shortDescription: "External embroidery subcontract, material issue challan, stock-at-worker tracking, and value reconciliation.",
    roles: ["Production", "Store", "Job Worker", "Quality", "Finance"],
    steps: [
      {
        stepNumber: 1,
        moduleId: "job-work",
        moduleName: "Job Work",
        title: "Issue Subcontract Order & Challan",
        description: "Create subcontract order for specialized chest logo embroidery; issue semi-finished panels.",
        role: "Production Planner",
        documentNumber: "JWO-2026-009",
        documentType: "JOB_WORK_ORDER",
        route: "/job-work/orders/jw-emb-01",
        badge: "ISSUED",
      },
      {
        stepNumber: 2,
        moduleId: "job-work",
        moduleName: "Job Work",
        title: "Track Stock at Subcontractor",
        description: "Maintain company ownership of material physically located at external Tirupur embroidery facility.",
        role: "Store Lead",
        documentNumber: "JWC-2026-015",
        documentType: "JOB_WORK_CHALLAN",
        route: "/job-work/orders/jw-emb-01",
        badge: "AT WORKER",
      },
      {
        stepNumber: 3,
        moduleId: "job-work",
        moduleName: "Job Work",
        title: "Receive Processed Panels & QC Check",
        description: "Verify embroidered quantity, record minor process loss, and match against agreed service rate.",
        role: "Quality & Finance",
        documentNumber: "JWR-2026-012",
        documentType: "JOB_WORK_RECEIPT",
        route: "/job-work/orders/jw-emb-01",
        badge: "RECONCILED",
      },
    ],
  },
};
